### ISSUE TITLE
Screen size/position issues (template or system?)

### ISSUE THREAD

**Issue by tmuray** [marshall62/mathspring#144]
1) The place where the topic and standard are shown on the screen needs to be moved down (or somewhere) because it overlaps with the area that can be used by hints. See figure attached.

2) Lynn:  the display area for the HTML templates is not the same as for the flash problems, and the HTML problems are taking up more area.  Thus the larger problem area is causing problems, for example the learning companion is in a weird place and sometimes the problem content needs to be scrolled to see it all.    

[this issue should be handled after the ONR and Affect tests this month]

![screen shot 2014-11-04 at 3 54 56 pm](https://cloud.githubusercontent.com/assets/6215165/4907955/e8c3f86e-6465-11e4-95e9-32c2a6006b2a.jpg)

**Comment by marshall62** [comment]
Fixed.  I had to move the topic info down further so that it didn't overlap bigger problems that occupy the full 600 pixel height of the div they play in.
