### ISSUE TITLE
animation_resource for short-answer problems

### ISSUE THREAD

**Issue by tmuray** [marshall62/mathspring#173]
text-only short answer problems (or quick-auth problems) don't use animation_resources.  Yet that field needs to be filled in.  REQUEST: allow that field to remain blank if it does nothing.

**Comment by marshall62** [comment]
OK.  For quickAuth problems we now ignore whats in the animationResource field and use the problem name in its place.   Remember that the problem name does have meaning.   If you are creating sound or using images in a quickAuth problem the problem's name will be the name of a directory underneath html5Probs where it goes to find sound and images.
