### ISSUE TITLE
Bug: timeInTutor is not computed correctly in StudentProblemHistory

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#182]
The latest students are the ones starting with username 'Rio'.
Try this query, where timeInTutor should increase for the same student, as I am sorting by studentproblemhistory.id. TimeIntutor drops when the session changes: 

SELECT studId, problemId, topicId, numMistakes, sessionid, studentproblemhistory.id, timeInTutor
FROM studentproblemhistory, probstdmap, standard, student 
WHERE username like 'Rio%' 
AND studentproblemhistory.problemId = probstdmap.probId AND probstdmap.stdId = standard.id 
AND student.id=studid
ORDER BY studId, topicId,  studentproblemhistory.id

**Comment by marshall62** [comment]
TimeInTutor measures the time from the beginning of a session to the time of the problem.   It doesn't measure overall time in the tutor across sessions.
