### ISSUE TITLE
In the next couple of days: Creating a second pedagogy for collaboration

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#183]
I have found so far a pedagogy called:

Collaboration Testing with Jane Full Empathy
I would like to change this one to have SEMI-Empathy instead of FULL-Empathy

We also need another one for Jake:
Collaboration Testing with Jake Semi Empathy

**Comment by IvonArroyo** [comment]
Actually, this is urgent. I did not realize that it is MONDAY that we are running the study.
This should be done today. 
See you later at the meeting.
--Ivon

**Comment by marshall62** [comment]
created
