### ISSUE TITLE
SPP deck of cards doesn't show for 'Univariate Equations'

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#185]
This is a strange one… When you click on the SPP to see more details about a topic, the SPP deck of cards doesn't show for 'Univariate Equations' but does for all other topics.

I tried adding activity in the topic, without any activity in the topic, doesn't matter what I do, it never shows up for that 'Univariate Equations' topic.

I wonder if it somehow is generating an exception for some reason? Can you check? It would have to be from 1:10-1:20PM today, April 7.

![screen shot 2015-04-07 at 1 16 28 pm](https://cloud.githubusercontent.com/assets/5631787/7029093/bdb17e08-dd28-11e4-8dfc-b8dd9bbde71c.png)

**Comment by mfrechet** [comment]
Fixed
