### ISSUE TITLE
Screen Info in Test mode that works for quick-auth problems

### ISSUE THREAD

**Issue by tmuray** [marshall62/mathspring#187]
code request: in Testing mode in the corner it shows problem info:
	• 1341:equilateralPerim1
	• Answer: undefined

1) can you add, for parameterized problems, which parameter set is used (e.g. "p-set 2")
2) can you show the answer here for short-answer problems?

**Comment by marshall62** [comment]
Instead of showing the name of the parameter set (which isn't available in the client) I show the variable bindings.    The answer should now have a setting when its a quickAuth problem
