### ISSUE TITLE
Quick-auth {brackets} notation for images--problem??

### ISSUE THREAD

**Issue by tmuray** [marshall62/mathspring#192]
We found a cool tool that creates HTML tags for equations (fraction, etc.). There is  WYSIWYG editor for math equations and it spits out HTML that can be pasted into Mathsprings.   The problem is that the HMTL it spits out includes {curly brackets}.  The quick-auth system may convert these into image tags.  So I think we need a new system for image tags.  Maybe {[imgagename.jpg]}  ??  Any single character will probably get us into trouble somewhere.   Also there is another issue #191 seems related to this problem, i.e. that curly brackets should not always be assumed to be an {image-file}. 

The concept of escaping the brackets /{    
won't work because this tool produces so many brackets!:  e.g.

<img src="http://latex.codecogs.com/png.latex?\fn_jvn&space;\large&space;7\tfrac{3}{5}&space;-&space;2\tfrac{1}{5}&space;=&space;5\tfrac{2}{5}" title="\large 7\tfrac{3}{5} - 2\tfrac{1}{5} = 5\tfrac{2}{5}" />

**Comment by tmuray** [comment]
The concept of escaping the brackets /{    
won't work because this tool produces so many brackets!:  e.g.

<imgg src="http://latex.codecogs.com/png.latex?\fn_jvn&space;\large&space;7\tfrac{3}{5}&space;-&space;2\tfrac{1}{5}&space;=&space;5\tfrac{2}{5}" title="\large 7\tfrac{3}{5} - 2\tfrac{1}{5} = 5\tfrac{2}{5}" />

**Comment by marshall62** [comment]
Melissa provided this feature.
