### ISSUE TITLE
Adding an external activity as an example

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#199]
Hi David, 

Could you please enter the first external activity into a topic, so that I see what are the tables involved, where things should go, etc.? Tom is not available to do this, and I would like these girls to try 1-2 on July 7th to see how they respond. 

There is 1 activity ready in mscontent, and I have a couple more to put into mscontent for other topics.  Could you please add in the one called "manhattanMosaic.html" that lives right now under:

mscontent/externalActivities/manhattanMosaic/manhattan.html

IT should go under the topic: Area of Polygons (topic number 2).

Questions that are preventing me from doing this are:
1) What is the URL of manhattan.html if currently those files live in rose under:
mscontent/externalActivities/manhattanMosaic/manhattan.html

Do any files need to be moved to somewhere else on rose or does Apache have direct access to the mscontent directory?

2) I don't really know the tables involved. I know they are not the same as a problem.

3) What is the criteria under which this external activity would show up right now? I know you set something by default.

If you do that one, I can add other ones following that same pattern.

--Ivon

**Comment by marshall62** [comment]
The files need to be pushed into gits mscontent repo.   I don't see anything in there.

**Comment by IvonArroyo** [comment]
It is there, check mscontent. Have you pulled? I added it a long time ago,
and it tells me there is "nothing to commit, working directory clean".

Listing should say:

drwxr-xr-x    5 iarroyo  staff    170 Apr 19 18:36 LearningCompanion
drwxr-xr-x  396 iarroyo  staff  13464 Apr 19 18:37 Problems
drwxr-xr-x    3 iarroyo  staff    102 Apr 20 10:44 externalActivities
drwxr-xr-x  130 iarroyo  staff   4420 May 29 09:48 html5Probs

Look inside externalActivities.

--Ivon



-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

**Comment by marshall62** [comment]
http://tutor.mathspring.org/mathspring/mscontent/externalActivities/manhattanMosaic/manhattan.html

is the URL to this activity.   So you can follow the instructions I sent and that should be put it into action.

**Comment by IvonArroyo** [comment]
Where are the instructions that you sent? Can you forward please?

--ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

**Comment by marshall62** [comment]
login to rose and go to
/mnt/net/http/mathspring/mscontent
and do :

git pull

This will put the files on the server where they are then accessed with a
URL like below

tutor.mathspring.org/mathspring/mscontent/html5Probs/problem_409/problem_409.html

Then you add entries to the externalactivity table and the
externalactivitytopic table to put them into our db. You can then reload
the server's problems with the teacher tools and they should be part of the
topic.


I don't know if Tom got around to turning off external activities that are
in the system and often cause problems because they are applets.    You'll
see this in the ready field
