### ISSUE TITLE
Student Progress Page: problems done=0

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#201]
Many of the topics show problems done=0, no plant or mastery bar,
although they had been working on the topic for a while. If you open
up "problem detail", you can see lots of problems done, with stars and
everything, but going back to the SPP it is as if they have never been
there

(one possibility to start fixing these bugs is to make a copy of
today's DB locally, and start debugging from those TF_350 and up
students).

In some cases, we were able to see problems done > 0 and activity
in the topic, but when we came back to see the SPP for a second time,
the information on that same topic was gone: 0 problems done.

**Comment by mfrechet** [comment]
Fixed
