### ISSUE TITLE
STudent Progress Page: Blank screen when looking at tiles for some topics

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#203]
"Inequalities" has no deck of cards at all, when you click on "learn more" to see the individual problems.
I believe "Univariate Equations" also has the same problem.

I think the fact that problems are sometimes part of 2 topics might be
at play here? Even though I tried to disable lots of double places. I
still think it is valuable to have problems in 2 or more topics.

**Comment by mfrechet** [comment]
Seems fixed
