### ISSUE TITLE
Student Progress Page: Icon on the tiles, *,  H or ! 

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#204]
Some Tiles were white, or marked incorrect. If you clicked on that problem tile, solved it correctly and clicked next problem, the tile would still have the previous state.
 
We should check this student called:  
Jordan	W	TF_383   pwd: TF

Download the latest DB, debug locally. She was having all these issues combined.

**Comment by mfrechet** [comment]
Fixed
