### ISSUE TITLE
Student Progress Page: Review and Challenge problems

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#205]
The review button did not show review problems that had been solved incorrectly, but probs. that have been solved correctly, or problems that had been never seen.

Once I tested, the last problem in the review mode kept coming back again and again.  

What about the challenge button? Was it really showing harder problems, at least at first?

**Comment by marshall62** [comment]
The review button shows all problems in the topic in order of difficulty. 

Challenge will try to show problems that begin with the students mastery level (or slightly below it) and get harder
