### ISSUE TITLE
External Activity shows together with instructions, should be after

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#206]
Hi David,

The External activity shows together with the instructions and covers the instructions, so they never get to read them until they close the window of the external activity.

External Activity should show up immediately after the student clicks OK in the instructions pop up.

--Ivon

**Comment by marshall62** [comment]
Ok.   This took a bit more work than you might think.   Now the instructions come up and when you click OK, it shows the external activity in a new browser window.

**Comment by IvonArroyo** [comment]
Thank you! I see it working.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute
