### ISSUE TITLE
Controlling when External Activity shows up

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#207]
Hi David,

How do I control when the external activity shows up? 

I logged in a second time, after seeing only 1 problem and it already showed up. That is too soon.

Should be something like after 10 minutes in the topic, 10 problems.

--Ivon

**Comment by marshall62** [comment]
The external activity intervention chooses an external activity 5% of the time (using a random number generator).  It doesn't repeat ones that a student has seen.   So the only way of controlling it is to turn down the percentage of time it chooses one but it's already pretty low so if you set it lower,  many students may never see one.

**Comment by IvonArroyo** [comment]
Hi DAvid,

This number looks fine, 5% chance.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute
