### ISSUE TITLE
Class Summary Per Problem Report: links to problems broken, some of them

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#210]
This report is very used in the classroom, to see the hardest problems, and some of the links to see the problems are broken.

http://rose.cs.umass.edu/woj/WoAdmin?action=AdminViewReport&teacherId=92&classId=1072&reportId=4&state=showReport

For instance this one:

http://tutor.mathspring.org/mathspring/mscontent/html5Probs/OrderOfOps_2/OrderOfOps_2.html

HTML ones take a looong time to load, not sure we can do something about this:
http://tutor.mathspring.org/mathspring/mscontent/html5Probs/problem_806/problem_806.html

--Ivon

**Comment by marshall62** [comment]
This report was broken in many ways.  I had to rewrite all the reports using a new chart package.  The URLs to problems should now work except for quickAuth problems which we do not have a way to preview yet (bug submitted about this).

**Comment by IvonArroyo** [comment]
Hi David,

I looked at the charts and they look amazing.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute
