### ISSUE TITLE
Test Users Generated when students are Generated

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#212]
There are different kinds of test users.

These test users are the ones that are generated for the teacher to test the system --generated together with the student user names (roster list).

These users should behave exactly like the student users so that the teacher (or people in the ground carrying out an experiment in California) can see exactly what students will see.

The only difference with a real student should be that their data is not saved in the problemstats table.

Currently, they are at least different in that the "test content" is selected, showing apparent bad system behavior that would not exist if a real student had logged in.

--Ivon

**Comment by marshall62** [comment]
We put a LOT of work into revamping the types of users and what they can see (guests, test, student, and even two types of Assistment users (test and real)).  People universally agreed that test users should see content that is marked "forTesting".  To test the system without this, we agreed that testers could login as guest user to try out the system as a student would see it.

I see why you'd want a student view that behaves as a student in a particular class.   The only way we can achieve this easily is to alter the behavior of users who register as test users.   When a new user goes to the signup page from the login screen they can create a user and click a button saying "for testing only".  Currently this type of user is shown a button that allows them to select problems and shows testable content.  Do you want me to change users who click this button to NOT SEE testable content and NOT SEE the button for selecting problems.   ????

This will mean that the only way to test the system in a particular class and see the tester controls will be to use the test user that is automatically generated for each pedagogy used by the class.

I think a better solution is to create some extra students in the class and use them for testing.   When you are done with a testUser, you can manually go into the database and set that user to isTrialUser=1.
This will have the effect of leaving that student out of reporting.

I suppose we could add a control to teacher tools for changing a user type from test to student but that could be dangerous .   

Let me know if this solves your question

**Comment by IvonArroyo** [comment]
OK, I found the testable user issue!  

Yes, definitely we want a type of user that, when a new user goes to the signup page from the login screen they can create a user and click a button saying "for testing only" that behaves exactly as a student user but does NOT pollute the probstats table, with no testable content.

This is also the kind of user that should be created with a class, when you generate student + "test" users for the class, as this is what teachers use to see how the system owuld behave for their students and should never see testable content.

--Ivon

**Comment by marshall62** [comment]
Currently test users do not pollute the data for a class.  They do not
affect the probstats table.  I thought your objection to test-users as they
are now working is that they see content marked as "testable".

**Comment by IvonArroyo** [comment]
Yes, both.  My objection is that there should be two kinds of test users, for testing the functionality of the system, and for testing content .

The problem is that, we test as researchers to see how the system works  we want test users to behave as real students, so we have been using real student users so far to test the functionality of the system, so that testable data is not present. For instance all of the collab1, 10 users that Melissa uses for testing. We used them last meeting also for testing.

In contrast, if we want to use the test users created for the class  (this is what teachers should use to see that the system works) they see an apparent broken system when the system might be fine because of content issues.

--Ivon

**Comment by IvonArroyo** [comment]
For instance all of the collab1, 10 users that Melissa uses for testing, but they are REAL students. We used them last meeting also for testing and have been polluting the database. We don't want broken content for this.

**Comment by marshall62** [comment]
OK.  I'll work on creating test users that can see the system as a student
would.
