### ISSUE TITLE
Firefox prevented this site from opening a pop-up window

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#217]
Even though videos pop-up fine, we got a message at the top when mini-games are supposed to show up:

Firefox prevented this site from opening a pop-up window

This is version 24.0

Is it being popped up in a different way than a video? 

This is also not caught is the math spring.org pop-up check (pop ups showed fine there).

--Ivon

**Comment by marshall62** [comment]
I don't understand.  Mini-games are external activities, right?   We run them in a browser window but don't have control over what kinds of things the mini-games are trying to do that might upset the browser.   So is this a question for Dovan to make sure her mini-games are not trying to do things that are getting blocked?   Mini-games aren't being shown when you click the show-video button are they?

**Comment by IvonArroyo** [comment]
Hi David,

How are you opening the mini-games window?  As a pop-up? as a new tab? As a
new window?

This is what happened: We were surprised that firefox complained saying
that pop-ups were blocked when actually the math spring pop-ups test run
perfectly well --but that was a test implemented by Evelyn at:
http://mathspring.org/to-use-mathspring/  and I don't trust anything she
did was right.

Possibly the popups  test is not correct?

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

---------- Forwarded message ----------

**Comment by marshall62** [comment]
I don't know what mini-games are.   I thought they were some things that
Dovan built and they were being used as external activities.   I don't know
how else a game would be part of mathspring (why would it be a video?).
So external activities are launched in a separate browser window right?
 So once the activity is running in that window and is trying to bring up
yet another window for pop-ups is that where things are misbehaving?

**Comment by IvonArroyo** [comment]
Let's talk at the meeting.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

On Wed, Oct 14, 2015 at 11:32 AM, marshall62 <notifications@github.com> <
SRS0=UZmc=KS=sgmail.github.com=bounces+848413-2b0e-iarroyo=wpi.edu@srs.wpi.edu

**Comment by marshall62** [comment]
I assume the mini-games are playing well since we went ahead with the experiment that uses them.  Please let me know if I can close this issue.

**Comment by IvonArroyo** [comment]
Hi Dovan,

let's please not close this issue yet. The experiment was postponed as
nobody debugged this enough.

The posttest is still an issue, it needs to show up and I don't think
anybody has tested the pre/posttest yet.

Meanwhile can you please send me the html code that pops-up either Dovan's
game and also the videos through the video button?  We need to make that
html code exactly as the test for pop-ups in mathspring.org. That was code
written by Evelyn and I don't know what it is testing but it is not pop-ups.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

**Comment by IvonArroyo** [comment]
I meant to say David and Dovan.

--I

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute
