### ISSUE TITLE
Pedagogies for Individual and Collaborative Mode need to ask for Frustration

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#221]
Hi David and Melissa,

At the affect meeting we agreed that this time, we want the pedagogies for individual and collaborative mode to ask for these two emotions: interest and frustration.

This means removing excitement and adding frustration.

Now, we want them to show up a little bit more often than before, one minute more often. What is the current setting of frequency of emotion requests right now?

--Ivon

**Comment by marshall62** [comment]
I am not sure which pedagogies you want to change.   In looking at pedagogies 44 and 45 which are ones with collab,  I do not see it having an AskEmotion intervention at all.

**Comment by IvonArroyo** [comment]
Yes, you are correct, it is 44 and 45, which are "collaboration Jane semi-empathy" and "collaboration Jake semi-empathy"

BUT we would also need to change the 2 control group pedagogies that are Jane/Jake semi-empathy (but these used to ask for frustration only I believe and they were created for another experiment). How about we clone those 2  pedagogies and create 2 new ones called "Individual with Jane Semi-Empathy" and "individual with Jake Semi-empathy" that ask for both frustration and interest, just like 44 and 45. 

The idea is that the ONLY difference between the "collaboration Jane semi-empathy" and "individual Jane semi-empathy" is the presence/absence of collaboration interventions.

Thank you David!

--Ivon

**Comment by marshall62** [comment]
Created 49 and 50 by cloning 3 and 4 and then changing the emotions to interest and frustration.   Please verify that 44, 45, 49, 50 are EXACTLY what you want.  I see some things in there that I'm not sure about (external activities in 44 and 49).   I do not see controls in the CollaborationIS that allows it to be offered more frequently.   I will ask Melissa to look into this and get back to you.

 <id>44</id>
        <name>Collaboration with Jane Semi Empathy</name>
        <comment>Students Collaborate on frustration/interest[3,3].   Also has moderately empathic female learning companion, asks about frustration/interest, external activities, highlights hint button</comment>
       
 <id>45</id>
        <name>Collaboration with Jake Semi Empathy</name>
        <comment>Students Collaborate on interest/frustration [3,3].   Also has moderately empathic male learning companion, asks about interest/frustration, highlight hint button</comment>
        
 <id>49</id>
        <name>Individual Jane Semi Empathy</name>
      <comment>highlight hint, ask about frustration and interest, external activities, Jane semi-empathy lc</comment>

 <id>50</id>
        <name>Individual Jake Semi Empathy</name>
        <comment>highlight hint, ask about frustration and interest, Jake semi-empathy lc</comment>

**Comment by mfrechet** [comment]
CollaborationIS doesn't control the AskEmotionInterventions at all.  Likely the frequency needs to be set in that intervention's selector.  I'll look into it.

**Comment by IvonArroyo** [comment]
Let me finalize the decision about the mini-games. In order to decide this,
I need to know what would happen if students are invited to collaborate on
the next problem, and the mini-game shows up instead of a problem on the
screen of the person that should get the shared problem.

Is the mini-game a candidate "problem" for collaboration, or are students
not supposed to collaborate on the mini-game --because it is a different
thing, like an introduction screen for instance?

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

**Comment by IvonArroyo** [comment]
Hi Melissa and David, let me post this here:

- Regarding past collaboration pilots in Turners and Camp Eureka: Collaboration was never supposed to be triggered by a certain emotion, or emotion level. It was supposed to be launched every fixed amount of problems/time. We said that a probability of 0.15 would be fine

- REgarding Turners and Camp Eureka: I thought that, even though we were not launching collaborations based on emotions or emotion levels, we still asked for emotions (at least interest/excitement). Was this not true?

- Regarding these new pedagogies and the upcoming study: Pedagogies look good in that we have to ask for frustration and interest in all four conditions.  However,  we should NOT launch collaborations based on emotion, but with a 0.15 probability REGADLESS of emotion. However emotion STILL needs to be asked for. 
Yes, please make these two emotions be asked a bit more often than we used to, which I think was every 5 minutes. 1 minute or even 30 seconds more often would help.
For the time being, disable mini-games in all pedagogies, I will ask you to create 2 different pedagogies to test the mini-games, for a different experiment, coming soon in a different "issue".

**Comment by IvonArroyo** [comment]
David, please let me know when these 4 pedagogies are available for testing, as I am creating usernames for everybody to test.

**Comment by mfrechet** [comment]
I'm unsure.  It depends on what the mini-games are seen as by the system. 
Only a problem will be candidate for collaboration.  Anyone know what the
mini-games are coded as?

> Let me finalize the decision about the mini-games. In order to decide
> this,
> I need to know what would happen if students are invited to collaborate on
> the next problem, and the mini-game shows up instead of a problem on the
> screen of the person that should get the shared problem.
>
> Is the mini-game a candidate "problem" for collaboration, or are students
> not supposed to collaborate on the mini-game --because it is a different
> thing, like an introduction screen for instance?
>
> --Ivon
>
> -----------
> Ivon Arroyo
> Assistant Professor
> Learning Sciences and Technologies
> Social Sciences and Policy Studies
> Salisbury Labs 317A
> Worcester Polytechnic Institute
>
> On Wed, Oct 14, 2015 at 1:21 PM, mfrechet <notifications@github.com> <

**Comment by mfrechet** [comment]
Ok; that clears that up, then.  In that case all I need to do is change a
variable.  I'll have it to David before tomorrow.

Melissa

**Comment by marshall62** [comment]
The pedagogies were created and I am assuming that they are defined appropriately (i.e. including external activities being included).   I am closing this issue.   If it turns out that you want something different about the pedagogies, please submit another issue about it.
