### ISSUE TITLE
Pedagogies for Mini-Games Study

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#222]
Hi David,

For the mini-games study (Dovan's external activities) we would need 3 pedagogies, with the following names and behaviors:

- Force Mini-Games --an external activity is selected for a topic, if any available, after 6 minutes in the topic (can you do this?). No characters. Ask about interest and frustration.
- Offer Mini-Games --an external activity is selected for a topic, if any available, after 6 minutes in the topic (can you do this?).  No characters. Ask about interest and frustration.
- No Mini-games --no external activities. No characters. Ask about interest and frustration.

**Comment by IvonArroyo** [comment]
Hi David,

These are the pedagogies that should be in place for the study that potentially starts next week...
I don't think it will start next week, realistically.
Definitely not if we don't have the pedagogies in place.
Could you please make this a high priority?
Thanks.

--Ivon

**Comment by marshall62** [comment]
Pedagogy 51 Asks about external acts
Pedagogy 52 Forces external acts
Pedagogy 53 has none.

All ask about interest/frustration.   None of them have LC.
There is no way to time external activities.  They are based on probability of being selected of 10%
