### ISSUE TITLE
Eliminating the "Process Mastery" Bar

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#225]
Hi David,

Could you please eliminate Tom's "Process Mastery" Line from the Charts. It is really confusing to have 2 lines sometimes saying different things.

I have to train teachers and keep telling people to ignore that line that is way too different from the other line. Too confusing for teachers to see and make sense of this.

--Ivon

**Comment by marshall62** [comment]
Yup.   That was something I was going to ask you about.  I'll comment out
the code so that when Tom asks for it back, it won't be a lot of work.

**Comment by IvonArroyo** [comment]
Sure :-)

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute
