### ISSUE TITLE
Posttest --how do we make it show up?

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#226]
Hi David,

How do we make the posttest show up?  Right now we can launch the pretest, but don't know how to set up when to run the posttest.

Ideally, the posttest would run after a certain time of tutor usage --such as after 45 minutes of use, OR at the beginning of the [3rd] day since they logged in.

Ideally, a combination of both (e.g. 10 minutes after logged in during the 3rd day).

What can we do for these studies coming up in about 4 weeks?

--Ivon

**Comment by IvonArroyo** [comment]
This is becoming a high priority, as we might need to run a study by the end of the week.  Making it show up after x minutes of login time is enough.

**Comment by marshall62** [comment]
Built a page in the teacher tools to turn on the post test since it is too complicated to try to figure it out based on time, days, etc.

**Comment by IvonArroyo** [comment]
Hi David,

I appreciate this feature, and I think it can be useful some times.

But I think this is not enough, unfortunately, and that we need a
time-based initiation of the posttest, depending on "time in tutor" a time
kept across sessions.

Many times we are not in the place where we are running the experiment,
such as in California, and cannot rely on teachers starting the posttest
through the teacher tools, making everybody log out, etc. We cannot do it
ourselves as we don't even know their schedules many times.

Could we please implement a time-based initiator of the posttest?

Ideally this check would be made every time they click on the new problem
button. Now, You said that it would be to "heavy" on the system to get a
check done at the "new problem" button. What about when students switch
topics, for instance?

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute
