### ISSUE TITLE
First time training a teacher: some bugs

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#227]
Hi David,

I faced some bugs in the teacher tools today after trying to train a teacher on how to create a user, classes, etc.

We first created a teacher user, and when she logged in with that user, she was an administrator instead of a normal teacher. This screwed things up, as we created a new class 1193 and got a lot of pedagogies and such. Then I realized that if she logged in again, she would get the standard mode instead of administrator, so I had her do that.

I tried to delete the class she created from the DB so that she would start over, but didn't manage, probably because of foreign keys. I quit that idea and had her modify the class instead and class 1193 is still there in the class table.

From there on, that class started behaving weird and generating exceptions all over the place. The teacher user is fmohsin/twins123. The class with issues is: 1193: MathSpring club-A

Changing settings on this class gives blank screens, which I assume are exceptions.

Can you take a look at this class and see what is going on?   Creating new classes now is apparently fine, even for that user.  

Maybe because we created the class as an administrator it is giving bugs?

--Ivon

**Comment by marshall62** [comment]
Ok.  It sounds like a real mess.   How do you go about creating the
teacher?  Do you add a row into the database by hand?   There is a table
called administrator and that should only be used for people like you, me,
tom and lynn.   Teachers should all go in the teacher table and then they
would login with the username and password in that table which should then
make the display be for a teacher and not an admin.   When you login with
your admin user/password it finds those in the administrator table and
that's how it knows to show you that interface.   I wouldn't be surprised
if there are bugs but I'm not sure I'll be able to find them without
knowing more about what users were logging in.

**Comment by marshall62** [comment]
OK.  I reproduced the error where the teacher logs in and gets the admin
screens.  I'm working on it.

**Comment by IvonArroyo** [comment]
Hi David,

I did everything from the teacher tools, except for trying to delete the
class that was created to start over (which I was unable to do). So I think
there are some real bugs.

Try creating a teacher user and logging in immediately after and see what
happens:

http://rose.cs.umass.edu/woj/WoAdmin?action=AdminTeacherLogin

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

On Fri, Oct 16, 2015 at 2:32 PM, marshall62 <notifications@github.com> <
SRS0=1nZ4=KU=sgmail.github.com=bounces+848413-2b0e-iarroyo=wpi.edu@srs.wpi.edu

**Comment by IvonArroyo** [comment]
OK, gotcha.  --I

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

On Fri, Oct 16, 2015 at 2:55 PM, marshall62 <notifications@github.com> <
SRS0=1nZ4=KU=sgmail.github.com=bounces+848413-2b0e-iarroyo=wpi.edu@srs.wpi.edu

**Comment by marshall62** [comment]
I just released a new Mathspring that should behave correctly in the
teacher tools when you login.
The teacher tools don't work so well for teachers who have 0 classes (new
teachers) and I had only tested them with teachers that had existing
classes and admins.   So I used the "create class" sequence of actions as
both types of users (teachers and admins) and for a teacher with No classes
and one with some classes and it does the correct thing.

The key thing, I guess, is that you have to be an admin if you want to use
the advanced pedagogy selection.   I'm going to add some other features to
the admin login so you can delete/add teachers and delete/add classes and
maybe students too.   It would be nice if we had a way to do some cleanup
when we wanted to.   And if its under admin users only, we shouldn't have
anybody using it who isn't aware of the risks.

**Comment by IvonArroyo** [comment]
Sounds perfect. Thanks!

Also, there is a bug in the teacher tools that, when you remove all topics
from the list of topics (in topic selection) gives an exception.

--I

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute
