### ISSUE TITLE
New Feature: Deleting a class 

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#228]
This would be very useful.

This would imply deleting the class, students for that class, and crawl over the DB to erase every data point for a student in the class.

This makes me nervous. How about instead we set a class as visible or erased? We then only show classes everywhere in the teacher tools that have "visible" on (or erased set to false).

--Ivon

**Comment by marshall62** [comment]
There are a LOT of classes that are lying around that were created for
testing only.   Also there are a lot of teachers lying around that are for
testing only.   It would be great to get them out of the database so they
don't keep appearing in lists.   So maybe we need both things.  A way to
delete the stuff we know is garbage and a way to mark stuff "invisible" if
we're not sure.

Unfortunately, there are a lot of classes that have been assigned to
pedagogies that no longer exist so if a user from that class tries to use
the system, they get an error about the pedagogy not existing.  So there is
a real problem with all this old stuff being in the system.

**Comment by marshall62** [comment]
Both things were done.   Classes have an isActive flag that allows us to hide them.  We also have a way to really delete a class in the teacher tools under adminstrative options.
