### ISSUE TITLE
Sent to different topic when worked no problems

### ISSUE THREAD

**Issue by lynn99** [marshall62/mathspring#234]
I was in the example problem for Decimals and Percents for a long time doing other things, and when I went back to it, got a message: You are about to switch topics because you have spent a lot of time in this topic. You have solved 0 of 0 problems.

I shouldn't be switched out of a topic if I have not yet attempted any problems. We know this topic has active problems.

**Comment by mfrechet** [comment]
This should be fixed with my next commit.  Let me know if the problem persists for anyone.
