### ISSUE TITLE
Can't click on anything in collab screens

### ISSUE THREAD

**Issue by lynn99** [marshall62/mathspring#235]
10-20-15 5:33 pm
lynnCollabLeft: Please wait while we find a partner for you...
You will discuss the problem together.
YOUR job is to use the mouse and keyboard.

lynnCollabRight: In this next problem, you will work with Lynn who should be sitting next to you, on Lynn's screen for ONE math problem.
Lynn will use the mouse and keyboard. Your job is to READ the math problem aloud on Lynn's screen.
Work together to solve the problem.

However, I can't get past these screens in either window. Clicking on Next Problem does nothing in either screen. Can't click on any buttons or links in either screen. I can, however, move the companion and the collab pop-up windows around, so they are not frozen.

**Comment by mfrechet** [comment]
Oh, I'm so sorry I didn't respond sooner.  I missed this last week and
just caught it now while I was double-checking emails received over the
last week.

I'll make this first priority; I'd thought I'd solved this bug awhile ago,
so it's disappointing to see it came back.  It's probably a timing issue
of some sort.

Thank you for the notification about it.

**Comment by lynn99** [comment]
Sorry Melissa, David saw it happen so I didn’t call it to your attention at the time. It may have been after you left because it was after the official end of the meeting.

—Lynn

**Comment by mfrechet** [comment]
Nothing to apologize for.  The bug was in GitHub, after all.

It does seem like the data was not saved for these users, save for in the
collaborationlog.  Unfortunately, some of the data I need to really debug
this would be in flankinguser or eventlog, so I'm going to have to try to
recreate the error, myself.  I will be using the same two users to see if
I can get it to happen.

Relevant question: Did you get any collaborations to work properly while
in the same session that this bug occurred?  If so, that would rule some
things out.

> Sorry Melissa, David saw it happen so I didn’t call it to your attention
> at the time. It may have been after you left because it was after the
> official end of the meeting.
>
> —Lynn
>
>
>
>
>

**Comment by lynn99** [comment]
Hi Melissa, 

Unfortunately, I didn’t have time to try a second time. So the answer is no, but probably meaningless for your purposes!

—Lynn

**Comment by mfrechet** [comment]
Hi Lynn,

    Ok.  In that case, are you 100% sure you entered the correct
neighbors?  That scenario will happen if one person enters a neighbor
who does not enter them in return.

Melissa

> Hi Melissa,
>
> Unfortunately, I didn’t have time to try a second time. So the answer is
> no, but probably meaningless for your purposes!
>
> —Lynn
>
>
>

**Comment by lynn99** [comment]
Yes, I entered my neighbors as lynnleft and lynnright.

Because the collab screens came up at almost the same time on both lynnleft and lynnright, I assumed I had entered them correctly?

—Lynn

**Comment by mfrechet** [comment]
We didn't specify a behavior for if one student enters it correctly but
the other enters it wrong, and said we would just be very careful to make
sure it didn't happen.  This means I didn't set up safety checks for this
condition, so the originator can trigger the screen for both students, but
the partner will never be able to complete confirming it, leaving both
frozen in the way you described.
If you are sure you entered them correctly, though, it must be something
else.  I just wish the partners had been saved to the database so I could
be sure, but I guess these were one of the varieties of test users, so it
didn't.  Regardless, I will attempt to duplicate the bug so I can fix it.

Melissa

> Yes, eh entered my neighbors as lynnleft and lynnright.
>
> Because the collab screens came up at almost the same time on both
> lynnleft and lynnright, I assuumed I had entered them correctly?
>
> —Lynn
>
>
>
>

**Comment by lynn99** [comment]
It may be that I entered the second one incorrectly.  I might have entered lynnleft instead of lynnright (or whatever the name was). Because the behavior you describe fits what happened.

I’m not sure I wrote down what I named the users, but if I can find it, I’ll try it when I get back into town. I’m at an out of town meeting for the rest of the week.

—Lynn

**Comment by mfrechet** [comment]
Hello,

  Don't bother looking into this.  On second thought, it would only hang
if the originating student entered the wrong partner, in which case it
wouldn't have shown up on the partner's screen.  I'm looking into this.

Melissa

> It may be that I entered the second one incorrectly.  I might have entered
> lynnleft instead of lynnright (or whatever the name was). Because the
> behavior you describe fits what happened.
>
> I’m not sure I wrote down what I named the users, but if I can find it,
> I’ll try it when I get back into town. I’m at an out of town meeting
> for the rest of the week.
>
> —Lynn
>
>
>
>
>

**Comment by lynn99** [comment]
Thanks!

—Lynn
