### ISSUE TITLE
error on problem #1392 , 8GB8_1 - not recognized

### ISSUE THREAD

**Issue by tmuray** [marshall62/mathspring#243]
HI Dave and Melissa,

Can you debug this soon?  Kevin just created a new problem #1392 , 8GB8_1. (note, we have stopped putting “problem_” in problem names).  (UPDATE: same problem with #1394)

I’ve uploaded the media OK onto rose, the problem is set to testable, and I did problem Reload in teacher tools.

But it does not show up in Mathspring: "Invalid problemId. Cannot find problem for 1392” (also does not show up in the tester's problem list popup within Mathspring)

Can you help debug this?

Also, from the previewer tool in the CMS it looks like the images in the problem are showing up oversized. If this does not happen in mathspring then ignore, but if it does happen in Mathspring, please advise on what we should do.

—thanks, Tom

**Comment by marshall62** [comment]
But it does not show up in Mathspring "Invalid problemId. Cannot find
problem for 1392”

What are you doing that generates this error?

**Comment by tmuray** [comment]
yes!—that’s the problem!
but why?


> On Oct 27, 2015, at 4:51 PM, marshall62 <notifications@github.com> wrote:
> 
> But it does not show up in Mathspring "Invalid problemId. Cannot find
> problem for 1392”
> 
> What are you doing that generates this error?
> 
> On Tue, Oct 27, 2015 at 4:27 PM, tmuray <notifications@github.com> wrote:
> 
> > HI Dave and Melissa,
> >
> > Can you debug this soon? Kevin just created a new problem #1392 , 8GB8_1.
> > (note, we have stopped putting “problem_” in problem names)
> >
> > I’ve uploaded the media OK onto rose, the problem is set to testable, and
> > I did problem Reload in teacher tools.
> >
> > But it does not show up in Mathspring "Invalid problemId. Cannot find
> > problem for 1392”
> >
> > Can you help debug this?
> >
> > Also, from the previewer tool in the CMS it looks like the images in the
> > problem are showing up oversized. If this does not happen in mathspring
> > then ignore, but if it does happen in Mathspring, please advise on what we
> > should do.
> >
> > —thanks, Tom
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/marshall62/mathspring/issues/243>.
> >
> —
> Reply to this email directly or view it on GitHub <https://github.com/marshall62/mathspring/issues/243#issuecomment-151639828>.
> 

===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===
Tom Murray, EdD

Senior Research Fellow in Cognitive Tools, Educational Technology & Online Communities  at UMass Amherst, and

Chief Visionary and Instigator at Perspegrity Solutions 

Home: 36 Fruit Street, Northampton MA 01060; phone: is413-then-695-and-2800 

www.tommurray.us <http://www.tommurray.us/>,  www.perspegrity.com <http://www.perspegrity.com/> (also tommurray.us@gmail.com <mailto:tommurray.us@gmail.com>)

**Comment by tmuray** [comment]
I am doing nothing to generate this error Dave. That’s why I’m asking you about it. As far as I can tell it should be working.  :-)


> On Oct 27, 2015, at 4:51 PM, marshall62 <notifications@github.com> wrote:
> 
> But it does not show up in Mathspring "Invalid problemId. Cannot find
> problem for 1392”
> 
> What are you doing that generates this error?
> 
> On Tue, Oct 27, 2015 at 4:27 PM, tmuray <notifications@github.com> wrote:
> 
> > HI Dave and Melissa,
> >
> > Can you debug this soon? Kevin just created a new problem #1392 , 8GB8_1.
> > (note, we have stopped putting “problem_” in problem names)
> >
> > I’ve uploaded the media OK onto rose, the problem is set to testable, and
> > I did problem Reload in teacher tools.
> >
> > But it does not show up in Mathspring "Invalid problemId. Cannot find
> > problem for 1392”
> >
> > Can you help debug this?
> >
> > Also, from the previewer tool in the CMS it looks like the images in the
> > problem are showing up oversized. If this does not happen in mathspring
> > then ignore, but if it does happen in Mathspring, please advise on what we
> > should do.
> >
> > —thanks, Tom
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/marshall62/mathspring/issues/243>.
> >
> —
> Reply to this email directly or view it on GitHub <https://github.com/marshall62/mathspring/issues/243#issuecomment-151639828>.
> 

===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===
Tom Murray, EdD

Senior Research Fellow in Cognitive Tools, Educational Technology & Online Communities  at UMass Amherst, and

Chief Visionary and Instigator at Perspegrity Solutions 

Home: 36 Fruit Street, Northampton MA 01060; phone: is413-then-695-and-2800 

www.tommurray.us <http://www.tommurray.us/>,  www.perspegrity.com <http://www.perspegrity.com/> (also tommurray.us@gmail.com <mailto:tommurray.us@gmail.com>)

**Comment by tmuray** [comment]
to add to this: the issue also happens for new problem 1394 as well.  They are set to testable and I did reload problems in Tchr-tools. But they do not show up in the list of "select problem" in Mathspring for a test user.

**Comment by marshall62** [comment]
THese did not have overallproblemdifficulty rows.
