### ISSUE TITLE
login screen First/Last day survey needs to open survey in new window/tab

### ISSUE THREAD

**Issue by tmuray** [marshall62/mathspring#245]
it looks like the buttons on the login screen  for first day and last day survey won’t work for the google forms, because they come up in the same window and the google form assumes the survey is in a new window and asks them to close that window when done.  

>>actually, I think this is already on your list David, but it really doesn't make sense to have the options for surveys before students log in, as they may be class-dependent, and also with the new system their UID's get inserted.

**Comment by marshall62** [comment]
Given how we do surveying now, I would think we could remove the buttons
from the login screen, right?

**Comment by tmuray** [comment]
yes!

Its harder to test the post survey in mathspring though.  I don’t know how to make it come up within mathspring. 

> On Oct 29, 2015, at 11:15 AM, marshall62 <notifications@github.com> wrote:
> 
> Given how we do surveying now, I would think we could remove the buttons
> from the login screen, right?
> 
> On Thu, Oct 29, 2015 at 11:05 AM, tmuray <notifications@github.com> wrote:
> 
> > it looks like the buttons on the login screen for first day and last day
> > survey won’t work for the google forms, because they come up in the same
> > window and the google form assumes the survey is in a new window and asks
> > them to close that window when done. (I logged this in github)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/marshall62/mathspring/issues/245>.
> >
> —
> Reply to this email directly or view it on GitHub <https://github.com/marshall62/mathspring/issues/245#issuecomment-152211029>.
> 

===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===
Tom Murray, EdD

Senior Research Fellow in Cognitive Tools, Educational Technology & Online Communities  at UMass Amherst, and

Chief Visionary and Instigator at Perspegrity Solutions 

Home: 36 Fruit Street, Northampton MA 01060; phone: is413-then-695-and-2800 

www.tommurray.us <http://www.tommurray.us/>,  www.perspegrity.com <http://www.perspegrity.com/> (also tommurray.us@gmail.com <mailto:tommurray.us@gmail.com>)
