### ISSUE TITLE
tutorbrain URLs are now broken

### ISSUE THREAD

**Issue by tmuray** [marshall62/mathspring#250]
As of some time last week the link I use to “show problem in mathspring” from the authoring tool no longer works and generates error messages.
Example:

http://tutor.mathspring.org/woj/TutorBrain?action=TeachTopic&problemId=1341&mode=Practice

The error includes:
"HTTP Status 500 - An exception occurred processing JSP page /problem_skeleton.jsp at line 2”

This is a global bug for all problems, and is not related to which problem.  

Error seems to have started Nov 17th

**Comment by marshall62** [comment]
I sent an email explaining this but got no response.  I will assume you are moving to the previewing method I suggested.
