### ISSUE TITLE
BUG urgent: Removing the first day survey and last day survey from login screen

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#252]
This is very confusing as the video is currently telling them to go for those buttons (and needs to be changed). I am afraid they will go do the wrong pretest.

Please remove the buttons at the top of the login screen called survey pretest and survey posttest.

Also, could we set the default pretest to be this one just in case:

https://docs.google.com/forms/d/1tnpQydLpbNj8isJZnYfsqLf4BXzm8r0Q-PSVha_VlDE/viewform?entry.59119022&entry.2079719744=%3Cuname%3E&entry.271329356&entry.1917834011&entry.1896544608&entry.1754702317&entry.1068755864&entry.1351250104&entry.2079076268&entry.2091207452=%3Cuid%3E

Could we set the default posttest to be this one just in case:
https://docs.google.com/forms/d/1bPEZdEZTIgKwGxLEXgDOIn_6jwDCDxecoNeeHURPGqI/viewform?entry.991629627&entry.847629462=%3Cuname%3E&entry.185434883&entry.1612409963&entry.1789301839&entry.1243760168&entry.707607884&entry.220728821&entry.1100262660&entry.1191942514&entry.1495104151&entry.1043695751&entry.849768208&entry.370814072&entry.704192930=%3Cuid%3E

**Comment by marshall62** [comment]
I removed the buttons from the login page.  I did a release so this fix is available now.
Tom puts survey URLs in the db for each class (or a global default).  So if your classes are not getting the right survey, let him know the correct URL and he can change it.

**Comment by IvonArroyo** [comment]
Thanks, yes I know how the URLs are placed, I copied them over from the
class he was working on to my new cloned class.
I am leaving those class that he was working on as prototype classes to
clone.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute
