### ISSUE TITLE
Bug: Classconfig doesn't carry over when cloning class

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#253]
Hi David,
When you clone a class, a bunch of the fields in classconfig don't get carried over.
The pretest and posttest URLs should get carried over, and also some other fields maybe that say 'alot', 'above0', etc.
I copied them by hand this time, so not urgent.
--Ivon

**Comment by marshall62** [comment]
Fixed.  I will release this after the experiement in Calif.  It's part of a bunch of changes I've made that would probably be too risky to release before an experiment.
