### ISSUE TITLE
Bug: Blank Examples (demos) in a sequence

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#254]
I think this might be because I am running out of problems, maybe. It never happened before.

Now I got 3 blank demo problems in a sequence. See screenshot, it is 4:18PM.

http://tutor.mathspring.org/woj/TutorBrain?action=MPPContinueTopic&sessionId=60929&eventCounter=1&topicId=4&studentAction=continue&comment=

Screenshot attached, for after the example window
![screen shot 2015-12-01 at 4 17 38 pm](https://cloud.githubusercontent.com/assets/5631787/11514612/622a4ac6-9847-11e5-8c95-5fd34423c36e.png)
 went away.

--Ivon

**Comment by marshall62** [comment]
This is very strange.  I went to the database eventlog so I could see all the things you did in this session (60929).   There are NO rows for this session.   I do not know how you could have used the system and have nothing in the eventlog table.   There is also no row in the session table for this (and other recent sessions).   Are you going in and deleting things?   This is very strange and worrying me.

**Comment by marshall62** [comment]
Let me know if you were logging in as a guest.   I don't see why you would have if you were trying to test collab

**Comment by mfrechet** [comment]
This probably is what happened.  It's the same thing I was mentioning at
the meeting about flankinguser data vanishing.

**Comment by marshall62** [comment]
The thing is guest users wouldn't be given a pedagogy involving collab so
I'm not sure why Ivon would have been doing that.

**Comment by marshall62** [comment]
The problem was that the cleanup demon was running and deleting the user data because they are a "test" user.   Fixed this.
