### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#259]
Hi David,

While talking to DoDEA, I remembered some login issues that David Yale faced  in CA, and I have been thinking for a while:

The Login page should have a clear distinction between login and sign up, which is not obvious to students, something like this:

"Do you have a username already?" Then enter them here  --> username/pwd boxes next to it
"Are you a student?  If you do not have a username and are a student, then "sign up" to your class" --> Sign in button
"Do you want to just try out the tutor?" Then click on Guest  --> Guest button.

--Ivon

**Comment by marshall62** [comment]
done
