### ISSUE TITLE
Report per Common Core Standard

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#262]
This was  a hit during the Dodea demo. It makes sense, teachers want to know what standards are the weakest for their students. There are a few changes/improvements that I outline regarding this:

1- It would be important to be able to "dig deeper" into which problems MathSpring gave for each cluster, especially for the rows highlighted yellow. The other "per custom made skill" report did this, by generating a link to the "Per Problem report" with the skill name, a link like this:
....action=AdminViewReport&teacherId=76&classId=1220&reportId=4&extraParam=33&state=showReport
with an extra parameter that corresponded to the filtered "skill".  We would need to ALSO modify the Per Problem Report so that it understands that the extra parameter "extraParam" can be a CC standard (e.g. 3.NS.1) instead of a plain skill number.

2- Bug: number of problems seems to be off, it must be showing number of hints --problem steps-- right now (this is a bug that might be carried from the previous report that had skills assigned to each hint). Each problem-student interaction should be counted once.

3- I assume that example (demo) problems are not part of this report?

4- There are some typos in the Common Core cluster name (missing spaces , a colon after the name, etc.)

**Comment by marshall62** [comment]
#1 OK.   Made the cluster names be links that take you to a report about that cluster.  The report will show the details of problems solved in that cluster.  
#2 Wrong:   For example class 1220 has results in the #Problems column .   Look at the result for
the cluster  38: "Grade-6: Area, Surface Area, and Volume" in the second row (colored yellow).  You will see it has 154 problems.   Here is the query that returns all the problems seen by students in this class that are practice problems and in cluster 38 .   You will see that it returns 154 rows.  You can verify other clusters by changing the cluster ID.  So I'm not sure why you think this is wrong.  Please provide evidence.   

select h.* from studentproblemhistory h, probstdmap m, standard s where h.studid in (select id from student where classid=1220)
and h.mode='practice' and h.problemid=m.probId and s.id=m.stdid and s.clusterid=38
