### ISSUE TITLE
Student Roster: Adding new users incrementally in batches

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#265]
Hi David, The teachers and other users have asked what happens if they created a batch of users and then want to add some more.
I know we cannot do this right now, but it seems very reasonable to want to add a new set of users, in batches. We can make the operation fail if some of the users in the new batch already exist in the old batch saying "at least some of those new users you want to create already exist".

--Ivon

**Comment by marshall62** [comment]
There is now an "Add Students" button which will allow creating more students in a class.
