### ISSUE TITLE
Bug (or sort of) in Avg. Learning Trajectory reports per class

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#269]
Hi David,

Tomorrow I am showing the teacher reports to David Yale, and have been looking at them in detail.

When you click at the column header of the "per topic" report (the one with the colored cells), you get a mean masgtery trajectory for the topic for the whole class right now.

The issue is that at the beginning of the chart you may have 15 kids averaged in a data point, and at the end of the chart you have a case/dot with only 1 kid. This skews the data terribly.

I am wondering if :+1: 

a) there is an easy way to display how many kids are being averaged at each data point? Either another line or a number somewhere?
b) can we just NOT PLOT (stop plotting) after the number of cases (number of kids averaged) is lower than 5?

Please let me know (how fast can this be done also)?

--Ivon

**Comment by marshall62** [comment]
I made it stop plotting data points if the number of students involved at that point in time is < 5.

I know that there are inconsistencies between the trajectory report and the per problem report which has numbers in the cells that look like [5/9].   In the past there have been bugs in the event log which make it hard to find practice problems.  Sometimes problems didn't get labelled as practice or they didn't have an endProblem event.  This is why the trajectory report often has less problems in it than the pre problem report - it goes through the eventlog simulating the student behavior in order compute mastery but if there is missing stuff in the event, it can't correctly consider the problem as part of the trajectory even though it maybe considered by the per problem report which doesn't rely on the eventlog.

**Comment by IvonArroyo** [comment]
I see, thank you! This should make a big difference.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute
