### ISSUE TITLE
After showing reports to a teacher: Text Messages and a few bugs in Main Teacher Tools Page

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#270]
This is very easy to do and very important, as teachers cannot understand what the reports or the interface mean after logging in. A small effort and a large benefit.

1- Main teacher tools Page --> Not clear what class you are in, or that the combo box is to change the class. This is what was suggested:
--> Change Class #: 1220 (top right) with the actual name of the class
--> Text next to the combo box should say (click here to change class -->)

**Comment by marshall62** [comment]
Fixed.
