### ISSUE TITLE
After showing reports to a teacher: Text Messages and a few bugs in the list of Reports to choose

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#271]
2- In the table of reports to choose:
a) remove the ones that are called "for researchers only" for the teacher accounts, and leave these for the administrator teacher accounts.
b) " Learning Hut Reports " should be changed to "Detailed Problem Solving Reports "
c) "Problems that are challenging for your students" should be changed by "Results for problems, for your whole class"
d) "Common Core clusters that your students are having trouble with" shoud be changed with "Results per Common Core Cluster, for your whole class"
e) "(will take a couple of minutes to run)  " should be removed, as it is coming up really quickly.
f) "Math skills that your students are having trouble with" should be changed with "Results in fine-grained level math skills, for your whole class"
g) "Mastery levels of topics" should be "How your students are mastering a variety of math topics"

**Comment by marshall62** [comment]
Fixed
