### ISSUE TITLE
Bug in StudentProblemHistory Table: TimeInTutor

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#283]
TimeInTutor in some data that we are looking at from past studies is more like TimeInSession. It goes down for the same student across sessions, while it should only go up, increase as the student uses the tutor more.

Please check this, has it been fixed already, or is it still broken?

--Ivon

**Comment by marshall62** [comment]
I'm seeing several bugs in this area.
I have a fix to this that has correct calculations but I see that both of these values are measured in milliseconds which get very large and could create an overflow.  

I propose the following change of units to the studentproblemhistory table

timeInTutor:  represents total time student has been in the tutor over all sessions.
   -  Lets change this to minutes.
timeInSession:  represents total time student has been in this session.
   - Lets change this to seconds.

**Comment by IvonArroyo** [comment]
This would be great.

Another possibility is that we store the day number, day 1, day 2, day 3,
etc, since the first time of login. I already can see lots of uses for that
variable in the teacher reports. Alternatively, we can store this is the
studentproblem history.

--Ivon

-----------
Ivon Arroyo
Assistant Professor in Social Sciences and Policy Studies
Assistant Professor in Computer Science
P.I. of the Advanced Learning Technologies Lab (http://alt.wpi.edu)
Learning Sciences and Technologies Graduate Program
(https://www.wpi.edu/academics/departments/learning-sciences-technologies)
Salisbury Labs 317A
Worcester Polytechnic Institute
-----------

**Comment by marshall62** [comment]
fixed.
