### ISSUE TITLE
BUG in Teacher Tools: Create class

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#290]
Hi David,

I tried to show teachers today in Holyoke how to create a class and got a blank screen (!). Not a good impression...

I got </error> for a web page after hitting submit to create a new class, in the public mathspring version (MS).

--Ivon

**Comment by IvonArroyo** [comment]
Everything breaks in the teacher tools when you create a class, you
cannot go anywhere.

It is ONLY after an error has been made when creating a class, and you
try to fix it.

See the two screens attached. From these errors, anything you try 
<img width="810" alt="screen shot 2016-09-27 at 11 32 20 am" src="https://cloud.githubusercontent.com/assets/5631787/18883663/15508d20-84b2-11e6-9a93-f69b2fcc5f55.png">
<img width="803" alt="screen shot 2016-09-27 at 11 31 21 am" src="https://cloud.githubusercontent.com/assets/5631787/18883664/155610ce-84b2-11e6-8f3c-b7100e5e7a54.png">

to
do gives a blank screen, even navigating around the page.

Really broken. Please fix ASAP, as I am showing teachers!

It would be OK to move the development tutor into the public tutor, if the major change has
only been the pretest.

**Comment by marshall62** [comment]
fixed.   The pages had a bug where the teacherId was lost after you submitted the first screen.
