### ISSUE TITLE
BUG in Student User Creation: Password too long

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#292]
When the password entered when creating a new user is too long, the system breaks and shows the SQL error.

This should be much more graceful, and check the length and report an error in a pop-up window before even attempting to create the user and fail entering it in the DB.

--Ivon

**Comment by marshall62** [comment]
I expanded the password field when I was converting the system to use hashed passwords.  

I tried a password "APasswordThatIsVeryLongAndICantImagineUsingAgain"  with no errors.  I think this should be sufficient.
