### ISSUE TITLE
BUG in Student User Creation: MathSpring Return to Login

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#293]
The button to return to the Login page, after creating a user gives a blank screen, instead of taking you to the login screen.

See screen attached to see where the button is, after creating a new user.

--Ivon
<img width="524" alt="screen shot 2016-09-30 at 4 13 14 pm" src="https://cloud.githubusercontent.com/assets/5631787/19005492/fa2eb958-8728-11e6-8806-a6cac85b0828.png">

**Comment by marshall62** [comment]
fixed
