### ISSUE TITLE
BUG in Pretest: Some questions/answers are too long --make fields in DB larger

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#303]
Hi David,

Some questions of the pretest are exceptionally long, have long choices.

The translation adds longer questions and answers also. See attached. I believe that making the field bigger in size, should solve the issue.

--Ivon
<img width="932" alt="screen shot 2016-11-28 at 2 44 46 pm" src="https://cloud.githubusercontent.com/assets/5631787/20683744/2998de50-b57b-11e6-84af-295bdba3abba.png">

**Comment by marshall62** [comment]
I changed the field widths in the database so that the problem description now accepts a max of 500 chars and the choice fields accept a max of 200 chars.  THey used to be 250 and 100 respectively.

I should point out that things will not look good if you put in long texts

**Comment by IvonArroyo** [comment]
Thank you, it seems to be working.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute
