### ISSUE TITLE
Bug in Full Empathy/Semi Empathy? No messages at beginning of problem displayed

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#304]
Hi David,

I have not managed to have a single message play at the beginning of a problem.
I have tried hard, used for a long time.

Try this user for instance : IvonTestPeriod5-3. It has Jane Full Empathy, but not a single message at the beginning of a problem has been shown. Neither the empathy messages acknowledging frustration / low confidence, nor the generalattribution messages.

I observed something similar for the semi-empathy condition.

Is this possibly a bug?

--Ivon

**Comment by marshall62** [comment]
I'm not seeing a problem.   I logged in with the user  IvonTestPeriod5-3 and see lots of learning companion messages.   See the eventlog for session 53877 and you will see many such emotions listed.   There have been no changes to any of the learning companion Java classes.   They seem to be working as they always have.

select * from eventlog where sessnum=63877

**Comment by IvonArroyo** [comment]
David,

There are no messages ever displayed at the beginning of a problem (only
solveTogether).

The messages that you see in the log are after an incorrect or correct
answer, not at the beginning of a problem.

There should be empathic messages at the beginning of a problem, at least
generalAttribution messages.

Can you please put a breakpoint and see why they are not showing up --Line
56/57 in EmpathicLC.java.

There is something STRANGE going on here, maybe the student model does not
record 'frustrated' any more or alike.

The experiment does not make sense in this case, all conditions would be
pretty much the same if there are no messages for empathy being displayed.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute
