### ISSUE TITLE
BUG in POSTTEST: Data truncation: Data too long for column 'studentAnswer' at row 1

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#307]
HI DAVID,

The open text answers should be a bit longer. I entered a somewhat long answer to an open-ended question, and got an exception, SQL:

Data truncation: Data too long for column 'studentAnswer' at row 1

**Comment by IvonArroyo** [comment]
Very nice otherwise. I just tested turning the posttest on and everything seems to be working well.

**Comment by marshall62** [comment]
Ok.  I doubled the size from 300 to 600 chars.   Wasn't sure if you meant
in the AskEmotion long answer or in the pretest long answer so I did it in
both.
