### ISSUE TITLE
ASAP pedagogy for GRIT: Change the emotion question

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#308]
David, as part of the initial pilot for the GRIT project, I will need to have a different kind of emotion question. I would need two pedagogies done so that I can videotape somebody such as my son:

This would be the same pedagogy that we have used so far in California, but the question of emotion should be a single one, that asks:

"Have you been hardworking recently in MathSpring?"
with the 5 point scale  we generally have, something like:
- I have definitely been hardworking recently
....
- Not at all hardworking recently

Thank you. I was going to do this over break, but then realized I needed a whole new pedagogy for it.

**Comment by IvonArroyo** [comment]
Two pedagogies for Jane/Jake

**Comment by marshall62** [comment]
Please give me the numbers of the two pedagogies you want to model these
after.   There were many that we created recently and I don't know which
ones to choose.

**Comment by marshall62** [comment]
Done.  Two new pedagogies are in the system for asking user about hardworking.

**Comment by IvonArroyo** [comment]
HI David,

They would be similar to 3 and 4, for instance. But I see that they are
done, thank you!

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute
