### ISSUE TITLE
ASAP Teacher tools bug in reports: Report per topic

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#309]
When I login to Hannen's class:

Unknown column 'timeToThirdHint' in 'field list'  exception in this report:

http://rose.cs.umass.edu/ms/WoAdmin?action=AdminViewReport&teacherId=690&classId=1279&reportId=23&state=showReport

I am trying to show reports to the teacher at Forest Grive but cannot as I get this bug.

--Ivon

**Comment by marshall62** [comment]
I fixed a typo in the name of that field in the db.  See if it works now.

**Comment by IvonArroyo** [comment]
Yeap, that fixed it,

thanks!  :-)

Happy new year! I hope you have started a good 2017 and that you got to
rest and spend time with your family and friends.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute
