### ISSUE TITLE
Bug in LOGS: Readme and isCorrect

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#316]
David, there are a few different ugly bugs here. see attached. One bug per ticket.

First, every time the student clicks "read me" the problem,  isSolved is always set to zero even if the student has solved correctly already.

<img width="892" alt="screen shot 2017-01-20 at 12 50 55 pm" src="https://cloud.githubusercontent.com/assets/5631787/22159524/50c258d6-df0f-11e6-841b-4ea3c67d2d42.png">

**Comment by marshall62** [comment]
Fixed.
