### ISSUE TITLE
Bug in Teacher Tools: Exception when creating a Teacher User

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#321]
Field 'oldpw' doesn't have a default value

--Ivon

**Comment by marshall62** [comment]
I'm not able to reproduce.  I used teacher tools to create a new teacher (hooha) and logged in with it.  I see that the teacher table has '' as the default value of oldpw.  

oldpw will need to go away soon.  It is only being kept until we are certain that no problems exist with people being able to login.

**Comment by rezecib** [comment]
@marshall62 Sorry, I fixed it during the meeting and forgot to check here. I set oldpw to have a default value of ""
