### ISSUE TITLE
Bug in LOGS: ProbElapsed goes to zero upon intervention

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#326]
I am continuing to post the bugs we found in this analysis of CA dataset.

This one (see screen attached) regards probelapsed.

ProbElapsed is logged as zero upon intervention of 'highlight hint button'.

Apparently the state of probelapsed is not lost, but the logging is incorrect, as then it recovers the probelapsed value (apparently) in the following
<img width="1207" alt="screen shot 2017-02-10 at 9 52 22 am" src="https://cloud.githubusercontent.com/assets/5631787/22831085/fdebee9c-ef76-11e6-9dc3-e034dac2e9cb.png">
 row.

See attached screenshot.
--Ivon

**Comment by marshall62** [comment]
Fixed.   We were ignoring the probElapsedTime in BeginIntervention events.   Now we log the value.
