### ISSUE TITLE
Bug in LOGS: HintStep value incorrect

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#328]
There are a few different things in this screenshot attached, I will post a ticket for each.

*** The hintStep should be NULL when the action was ‘attempt’. It should only have a value when the action is ‘hint’. 

<img width="1104" alt="hintnotnull" src="https://cloud.githubusercontent.com/assets/5631787/22837915/a2859052-ef90-11e6-8060-09a5f3f7173c.png">

**Comment by marshall62** [comment]
Fixed.  Attempts will not have a hintstep or hintid.
