### ISSUE TITLE
Bug in LOGS: isCorrect for ReadProblem

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#329]
There are a few different things in this screenshot attached, I will post a ticket for each.

ReadProblem should have isCorrect=1, it loses the correct state? or it keeps the state but the logging is wrong?

<img width="1104" alt="hintnotnull" src="https://cloud.githubusercontent.com/assets/5631787/22837950/cc39069a-ef90-11e6-8cb5-3df4cb2571cd.png">

**Comment by marshall62** [comment]
Some logged entries were always setting isCorrect to false.   All events now log the value for isCorrect based on whether the current problem is solved or not.
