### ISSUE TITLE
Bug in LOGS: ProblemID Changes for one single row

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#331]
ProblemID changes to 486 just for one row, for the Ask Emotion Intervention, even though the problem ID seems to be 1265. Where did that ID come from?

<img width="841" alt="problemidchanges" src="https://cloud.githubusercontent.com/assets/5631787/22838048/49d290b2-ef91-11e6-9b7c-332d90709228.png">

**Comment by marshall62** [comment]
Fixed.   This was a problem with the student state have bad value
