### ISSUE TITLE
Why do I keep getting this message when logging in as guest?

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#340]
![screen shot 2017-03-15 at 2 52 12 pm](https://cloud.githubusercontent.com/assets/5631787/23965669/1972e724-098f-11e7-9fb7-832d35e1365e.png)
See the message attached.

--Ivon

**Comment by marshall62** [comment]
This must be related to the URL redirects that were put in place.  The message has never come up before.
