### ISSUE TITLE
Bug in SPP : Go back to tutor exception

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#341]
I found one bug that kept repeating for students in the SPP:

When students clicked on the "go back to tutor" link at the top right of the page, an exception was always thrown, saying:

ack=false&message=null   or alike. Just that.

This would throw students off because they did not know what to do from there. Reloading would give the same thing of course, they just had to click the back button and choose to 'continue' instead.

 At least for any student in classes 1310 or 1311 (Susan Tarallo's classes).

Could we fix this as soon as possible, release a new ms, and I test today to make sure that it is fine to be used next week?

LOTS of students run into this bug, I guess it is intuitive for them to use the go back to tutor link, instead of choosing a topic to continue.

--Ivon

**Comment by marshall62** [comment]
Bug was caused by clicking MPP when in a Topic Intro and then trying to return to the tutor and it couldn't figure out what to do.   It now moves on correctly - usually to the demo problem following the topic intro.

**Comment by IvonArroyo** [comment]
Great that you figured it out.

--Ivon

-----------
Ivon Arroyo
Assistant Professor in Social Sciences and Policy Studies
Assistant Professor in Computer Science
P.I. of the Advanced Learning Technologies Lab (http://alt.wpi.edu)
Learning Sciences and Technologies Graduate Program
(https://www.wpi.edu/academics/departments/learning-sciences-technologies)
Salisbury Labs 317A
Worcester Polytechnic Institute
-----------
