### ISSUE TITLE
Change in MiniGames Ask: Put the percent frequency back to 10%

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#342]
In Millbury, the games are almost not showing at all.

This probably means that the random number generator is working properly, as it is set to 5% now.

Students are working very slowly through problems, very focused.

Can you please set the percent chance  of games showing up back to 10%?

Thanks, sorry I made you change this in the first place.

--Ivon

**Comment by marshall62** [comment]
both mini games pedagogies now use 10 percent
