### ISSUE TITLE
Teacher Tools: Problem Preview not working in PER-ROBLEM REPORT

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#346]
Really important as teachers cannot preview all problems in the reports any more.  We need this solved really soon, as I cannot show the reports to the teachers that are using with their students, for instance., showing where student gaps are regarding specific math problems.

 Report (Per Problem). Currently, it is only showing Flash Problems
correctly. Neither HTML nor Quick Author Problems are launching
correctly, it incorrectly attempts to launch a problem as a Flash
problem. Same as before, either the link changes, or if it is not
launchable, it should have a link to an image of the problem.

Try teacher
usr: Susan  pwd: Tarallo, 

and this report per problem:

http://tutor.mathspring.org/ms/WoAdmin?action=AdminViewReport&teacherId=705&classId=1310&reportId=4&state=showReport

You will see that there are many problems that are launching a flash
player when they seem to be something else (not flash) such as:

6RPA1_1: Ratio and Proportation: Games at recess
6RPA1_2: Ratio and Proportion: Games at recess 2
6RPA1_3: Ratio and Proportation: Games at recess - Short Answer
Exponent_1: exp1

Different kind of error here:
OrderOfOps_2: oo2

Pretty much everything you click on tries to launch a flash player,
which makes it unusable right now.  I am holding showing the reports
to the two teachers using it until this is fixed.

**Comment by rezecib** [comment]
I believe the [latest commit](https://github.com/marshall62/mathspring/commit/52d89f8c0147d7b15ec9df9134db268fbfc286cd) fixes this, however my local testing environment was not 100% adequate, so if @marshall62 could test it briefly before pushing it live, that would be appreciated.
