### ISSUE TITLE
DROP hint constraint in Per Common Core Cluster Report (NTT)

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#363]
Hi neeraj,

I think we should DROP  the hint constraint for the per common core cluster report, as right now nothing gets painted for a real class. Sorry to change this again, you would have to change the label also.

--ivon

**Comment by nsmenon** [comment]
I saw very few records being labeled as "Orange" after changing the highlighting rule for the second time. I think some of the records were getting highlighted during our CKC meeting on Wednesday as well.
Do you think I should change the rule and filter it only on basis of "no of problems got right in first attempt only" ?
--
Neeraj

**Comment by IvonArroyo** [comment]
yes, I think so.

--Ivon

-----------
Ivon Arroyo
Assistant Professor in Social Sciences and Policy Studies, Computer
Science, Data Science and Interactive Media & Game Development
P.I. of the Advanced Learning Technologies Lab (http://alt.wpi.edu)
Learning Sciences and Technologies Graduate Program
(https://www.wpi.edu/academics/departments/learning-sciences-technologies)
Salisbury Labs 312
Worcester Polytechnic Institute
-----------
