### ISSUE TITLE
Bug, please fix: First topic after login selected from SPP

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#391]
Hi David,

There is a bug that is pretty obnoxious: if a student logs in and goes to the Student Progress Page, and choose a topic that is NOT the first one and click 'Try This', they get sent to the first topic anyways. It is very annoying and also teachers are encountering it as they want to choose specific topics to test problems as a student.

Can you fix this bug?

--Ivon

**Comment by marshall62** [comment]
Fixed.  If SPP is used to choose a new topic at beginning of session, it will now go to that topic when entering practice area.
